package com.pad.entity;
// Generated 2016-7-14 11:26:15 by Hibernate Tools 4.3.1.Final

import javax.persistence.Entity;

/**
 * Person generated by hbm2java
 */
@Entity(name = "Person")
public class Person implements java.io.Serializable {

	private int Age;
	private String Name;

	public Person() {
	}

	public Person(int Age) {
		this.Age = Age;
		
	}

	public Person(int Age, String Name) {
		this.Age = Age;
		this.Name = Name;
	}

	public int getAge() {
		return this.Age;
	}

	public void setAge(int Age) {
		this.Age = Age;
	}

	public String getName() {
		return this.Name;
	}

	public void setName(String Name) {
		this.Name = Name;
	}

}
